import type {
  AnaliticaInstitucional,
  Convocatoria,
  Postulacion,
  Proyecto,
  Publicacion,
  ResultadoMatch,
  Semillero,
} from "@/types/api";

/** Datos de demostración usados únicamente cuando el backend no responde. */

export const semillerosDemo: Semillero[] = [
  {
    idSemillero: 4,
    nombre: "Semillero de Inteligencia Artificial Aplicada",
    descripcion:
      "Investigación en aprendizaje automático aplicado a problemas de salud pública y analítica urbana en el Valle de Aburrá.",
    lineasInvestigacion: ["Machine Learning", "Visión por Computador", "Analítica de Datos"],
    estado: "ACTIVO",
    facultad: "Facultad de Ingeniería",
    lideres: [],
    totalProyectos: 6,
    totalPublicaciones: 11,
    totalIntegrantes: 18,
    convocatoriaAbierta: true,
  },
  {
    idSemillero: 7,
    nombre: "Semillero de Salud Pública y Epidemiología",
    descripcion:
      "Estudios poblacionales sobre determinantes sociales de la salud y vigilancia epidemiológica territorial.",
    lineasInvestigacion: ["Epidemiología", "Bioestadística", "Políticas Públicas"],
    estado: "ACTIVO",
    facultad: "Facultad de Medicina",
    lideres: [],
    totalProyectos: 4,
    totalPublicaciones: 9,
    totalIntegrantes: 14,
    convocatoriaAbierta: true,
  },
  {
    idSemillero: 12,
    nombre: "Semillero de Materiales Avanzados",
    descripcion:
      "Caracterización de materiales cerámicos y compuestos para aplicaciones industriales sostenibles.",
    lineasInvestigacion: ["Ciencia de Materiales", "Nanotecnología"],
    estado: "ACTIVO",
    facultad: "Facultad de Ciencias Exactas y Naturales",
    lideres: [],
    totalProyectos: 3,
    totalPublicaciones: 7,
    totalIntegrantes: 9,
    convocatoriaAbierta: false,
  },
  {
    idSemillero: 15,
    nombre: "Semillero de Estudios Jurídicos y Derechos Humanos",
    descripcion:
      "Análisis normativo y jurisprudencial en materia de derechos humanos y justicia transicional.",
    lineasInvestigacion: ["Derecho Constitucional", "Derechos Humanos"],
    estado: "EN_PAUSA",
    facultad: "Facultad de Derecho y Ciencias Políticas",
    lideres: [],
    totalProyectos: 2,
    totalPublicaciones: 5,
    totalIntegrantes: 11,
    convocatoriaAbierta: false,
  },
  {
    idSemillero: 18,
    nombre: "Semillero de Economía Regional",
    descripcion:
      "Modelos econométricos aplicados al desarrollo regional antioqueño y a la medición de la pobreza multidimensional.",
    lineasInvestigacion: ["Econometría", "Desarrollo Regional"],
    estado: "ACTIVO",
    facultad: "Facultad de Ciencias Económicas",
    lideres: [],
    totalProyectos: 5,
    totalPublicaciones: 8,
    totalIntegrantes: 13,
    convocatoriaAbierta: true,
  },
];

export const convocatoriasDemo: Convocatoria[] = [
  {
    idConvocatoria: 31,
    idSemillero: 4,
    nombreSemillero: "Semillero de Inteligencia Artificial Aplicada",
    titulo: "Vinculación 2026-2 en aprendizaje automático",
    descripcion:
      "Se buscan estudiantes con fundamentos en programación y estadística para apoyar dos proyectos activos.",
    fechaApertura: "2026-08-01",
    fechaCierre: "2026-09-30",
    cuposTotales: 6,
    cuposDisponibles: 2,
    estado: "ABIERTA",
    habilidadesRequeridas: ["Python", "Machine Learning", "Redacción Académica"],
  },
  {
    idConvocatoria: 34,
    idSemillero: 7,
    nombreSemillero: "Semillero de Salud Pública y Epidemiología",
    titulo: "Auxiliares de investigación en vigilancia epidemiológica",
    descripcion: "Apoyo en recolección y análisis de datos poblacionales.",
    fechaApertura: "2026-08-15",
    fechaCierre: "2026-10-15",
    cuposTotales: 4,
    cuposDisponibles: 3,
    estado: "ABIERTA",
    habilidadesRequeridas: ["Bioestadística", "R", "Trabajo de Campo"],
  },
  {
    idConvocatoria: 38,
    idSemillero: 18,
    nombreSemillero: "Semillero de Economía Regional",
    titulo: "Convocatoria en econometría aplicada",
    descripcion: "Modelado de series de tiempo para indicadores regionales.",
    fechaApertura: "2026-09-01",
    fechaCierre: "2026-10-05",
    cuposTotales: 3,
    cuposDisponibles: 1,
    estado: "ABIERTA",
    habilidadesRequeridas: ["Stata", "Econometría", "Análisis de Datos"],
  },
];

export const postulacionesDemo: Postulacion[] = [
  {
    idPostulacion: 501,
    idConvocatoria: 31,
    tituloConvocatoria: "Vinculación 2026-2 en aprendizaje automático",
    nombreSemillero: "Semillero de Inteligencia Artificial Aplicada",
    idEstudiante: 88,
    nombreEstudiante: "Laura Restrepo Gómez",
    programaEstudiante: "Ingeniería de Sistemas",
    estado: "PRE_APROBADA",
    fechaPostulacion: "2026-09-02T10:12:00Z",
    fechaPreAprobacion: "2026-09-10T14:30:00Z",
    fechaDecisionEstudiante: null,
    porcentajeMatch: 92.5,
    habilidades: ["Python", "Machine Learning"],
    cartaMotivacion: "Interés en aplicar modelos predictivos a problemas de salud pública.",
  },
  {
    idPostulacion: 502,
    idConvocatoria: 34,
    tituloConvocatoria: "Auxiliares de investigación en vigilancia epidemiológica",
    nombreSemillero: "Semillero de Salud Pública y Epidemiología",
    idEstudiante: 88,
    nombreEstudiante: "Laura Restrepo Gómez",
    programaEstudiante: "Ingeniería de Sistemas",
    estado: "EN_REVISION",
    fechaPostulacion: "2026-09-05T09:00:00Z",
    porcentajeMatch: 71.4,
    habilidades: ["Análisis de Datos"],
  },
  {
    idPostulacion: 503,
    idConvocatoria: 38,
    tituloConvocatoria: "Convocatoria en econometría aplicada",
    nombreSemillero: "Semillero de Economía Regional",
    idEstudiante: 91,
    nombreEstudiante: "Andrés Villa Cardona",
    programaEstudiante: "Economía",
    estado: "ACEPTADA_POR_ESTUDIANTE",
    fechaPostulacion: "2026-09-06T16:45:00Z",
    fechaPreAprobacion: "2026-09-11T08:20:00Z",
    fechaDecisionEstudiante: "2026-09-12T11:05:00Z",
    porcentajeMatch: 84.0,
    habilidades: ["Econometría", "Stata"],
  },
  {
    idPostulacion: 504,
    idConvocatoria: 31,
    tituloConvocatoria: "Vinculación 2026-2 en aprendizaje automático",
    nombreSemillero: "Semillero de Inteligencia Artificial Aplicada",
    idEstudiante: 95,
    nombreEstudiante: "Mariana Ospina Zapata",
    programaEstudiante: "Estadística",
    estado: "CANCELADA_EN_CASCADA",
    fechaPostulacion: "2026-08-28T12:00:00Z",
    fechaPreAprobacion: "2026-09-04T10:00:00Z",
    fechaDecisionEstudiante: "2026-09-09T09:15:00Z",
    porcentajeMatch: 78.2,
    habilidades: ["R", "Modelado de Datos"],
  },
];

export const matchesDemo: ResultadoMatch[] = [
  {
    idSemillero: 4,
    nombre: "Semillero de Inteligencia Artificial Aplicada",
    porcentajeMatch: 92.5,
    factoresCoincidencia: ["Python", "Machine Learning", "Convocatoria Activa"],
    desglose: {
      habilidades: 38,
      areasEspecialidad: 21.5,
      convocatoriaAbierta: 20,
      proximidadTematica: 13,
    },
    convocatoriaAbierta: true,
    facultad: "Facultad de Ingeniería",
  },
  {
    idSemillero: 18,
    nombre: "Semillero de Economía Regional",
    porcentajeMatch: 76.8,
    factoresCoincidencia: ["Análisis de Datos", "Convocatoria Activa"],
    desglose: {
      habilidades: 27,
      areasEspecialidad: 17.8,
      convocatoriaAbierta: 20,
      proximidadTematica: 12,
    },
    convocatoriaAbierta: true,
    facultad: "Facultad de Ciencias Económicas",
  },
  {
    idSemillero: 7,
    nombre: "Semillero de Salud Pública y Epidemiología",
    porcentajeMatch: 68.3,
    factoresCoincidencia: ["Bioestadística", "Interdisciplinariedad"],
    desglose: {
      habilidades: 24,
      areasEspecialidad: 15.3,
      convocatoriaAbierta: 20,
      proximidadTematica: 9,
    },
    convocatoriaAbierta: true,
    facultad: "Facultad de Medicina",
  },
  {
    idSemillero: 12,
    nombre: "Semillero de Materiales Avanzados",
    porcentajeMatch: 41.2,
    factoresCoincidencia: ["Modelado de Datos"],
    desglose: {
      habilidades: 18,
      areasEspecialidad: 12.2,
      convocatoriaAbierta: 0,
      proximidadTematica: 11,
    },
    convocatoriaAbierta: false,
    facultad: "Facultad de Ciencias Exactas y Naturales",
  },
];

export const proyectosDemo: Proyecto[] = [
  {
    idProyecto: 210,
    idSemillero: 4,
    titulo: "Predicción de demanda hospitalaria con series temporales",
    estado: "EN_CURSO",
    fechaInicio: "2026-02-10",
    fechaFin: null,
    presupuestoAsignado: 18500000,
    integrantes: 6,
  },
  {
    idProyecto: 214,
    idSemillero: 4,
    titulo: "Detección de anomalías en movilidad urbana",
    estado: "FINALIZADO",
    fechaInicio: "2025-03-01",
    fechaFin: "2026-01-20",
    presupuestoAsignado: 12000000,
    integrantes: 4,
  },
];

export const publicacionesDemo: Publicacion[] = [
  {
    idPublicacion: 88,
    idSemillero: 4,
    titulo: "Modelos de aprendizaje profundo para triage hospitalario",
    tipo: "Artículo en revista indexada",
    anio: 2026,
    doi: "10.1016/j.agora.2026.01.004",
    enlace: null,
    autores: [
      { nombre: "Carlos Mejía Ruiz", rolAutoria: "Autor principal", esEstudiante: false },
      { nombre: "Laura Restrepo Gómez", rolAutoria: "Coautora", esEstudiante: true },
    ],
  },
  {
    idPublicacion: 92,
    idSemillero: 4,
    titulo: "Analítica de movilidad urbana en el Valle de Aburrá",
    tipo: "Ponencia en congreso",
    anio: 2025,
    doi: null,
    enlace: "https://repositorio.udea.edu.co/agora/92",
    autores: [
      { nombre: "Mariana Ospina Zapata", rolAutoria: "Autora principal", esEstudiante: true },
    ],
  },
];

export const analiticaDemo: AnaliticaInstitucional = {
  kpis: {
    totalSemilleros: 148,
    semillerosActivos: 121,
    convocatoriasAbiertas: 27,
    postulacionesActivas: 412,
    tasaDemandaPromedio: 3.4,
    tiempoRespuestaEstudianteHoras: 38.6,
    tasaRechazoOfertas: 17.2,
    indiceConversionProyectoPublicacion: 1.6,
    participacionEstudiantilAutorias: 43.8,
    indiceInterdisciplinariedad: 29.5,
  },
  demandaPorSemillero: [
    {
      idSemillero: 4,
      nombre: "Inteligencia Artificial Aplicada",
      cuposOfertados: 6,
      postulacionesRecibidas: 41,
      tasaDemanda: 6.83,
    },
    {
      idSemillero: 7,
      nombre: "Salud Pública y Epidemiología",
      cuposOfertados: 4,
      postulacionesRecibidas: 19,
      tasaDemanda: 4.75,
    },
    {
      idSemillero: 18,
      nombre: "Economía Regional",
      cuposOfertados: 3,
      postulacionesRecibidas: 12,
      tasaDemanda: 4.0,
    },
    {
      idSemillero: 12,
      nombre: "Materiales Avanzados",
      cuposOfertados: 5,
      postulacionesRecibidas: 9,
      tasaDemanda: 1.8,
    },
    {
      idSemillero: 15,
      nombre: "Estudios Jurídicos y Derechos Humanos",
      cuposOfertados: 6,
      postulacionesRecibidas: 7,
      tasaDemanda: 1.17,
    },
  ],
  reconocimientos: [
    { ambito: "LOCAL", total: 34 },
    { ambito: "NACIONAL", total: 21 },
    { ambito: "INTERNACIONAL", total: 8 },
  ],
  habilidadesEmergentes: [
    { nombre: "Python", totalAceptadas: 64 },
    { nombre: "Análisis de Datos", totalAceptadas: 51 },
    { nombre: "Redacción Académica", totalAceptadas: 44 },
    { nombre: "Bioestadística", totalAceptadas: 29 },
    { nombre: "Modelado de Datos", totalAceptadas: 23 },
    { nombre: "Trabajo de Campo", totalAceptadas: 17 },
  ],
};
