/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnaliticaRouteImport } from './routes/analitica'
import { Route as CompatibilidadRouteImport } from './routes/compatibilidad'
import { Route as PostulacionesRouteImport } from './routes/postulaciones'
import { Route as AuthCompleteProfileRouteImport } from './routes/auth.complete-profile'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthSelectRoleRouteImport } from './routes/auth.select-role'
import { Route as SemillerosIndexRouteImport } from './routes/semilleros.index'
import { Route as SemillerosIdSemilleroRouteImport } from './routes/semilleros.$idSemillero'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliticaRoute = AnaliticaRouteImport.update({
  id: '/analitica',
  path: '/analitica',
  getParentRoute: () => rootRouteImport,
} as any)
const CompatibilidadRoute = CompatibilidadRouteImport.update({
  id: '/compatibilidad',
  path: '/compatibilidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PostulacionesRoute = PostulacionesRouteImport.update({
  id: '/postulaciones',
  path: '/postulaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteProfileRoute = AuthCompleteProfileRouteImport.update({
  id: '/auth/complete-profile',
  path: '/auth/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSelectRoleRoute = AuthSelectRoleRouteImport.update({
  id: '/auth/select-role',
  path: '/auth/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const SemillerosIndexRoute = SemillerosIndexRouteImport.update({
  id: '/semilleros/',
  path: '/semilleros/',
  getParentRoute: () => rootRouteImport,
} as any)
const SemillerosIdSemilleroRoute = SemillerosIdSemilleroRouteImport.update({
  id: '/semilleros/$idSemillero',
  path: '/semilleros/$idSemillero',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analitica': typeof AnaliticaRoute
  '/compatibilidad': typeof CompatibilidadRoute
  '/postulaciones': typeof PostulacionesRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/select-role': typeof AuthSelectRoleRoute
  '/semilleros/$idSemillero': typeof SemillerosIdSemilleroRoute
  '/semilleros/': typeof SemillerosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analitica': typeof AnaliticaRoute
  '/compatibilidad': typeof CompatibilidadRoute
  '/postulaciones': typeof PostulacionesRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/select-role': typeof AuthSelectRoleRoute
  '/semilleros/$idSemillero': typeof SemillerosIdSemilleroRoute
  '/semilleros': typeof SemillerosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analitica': typeof AnaliticaRoute
  '/compatibilidad': typeof CompatibilidadRoute
  '/postulaciones': typeof PostulacionesRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/select-role': typeof AuthSelectRoleRoute
  '/semilleros/$idSemillero': typeof SemillerosIdSemilleroRoute
  '/semilleros/': typeof SemillerosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analitica'
    | '/compatibilidad'
    | '/postulaciones'
    | '/auth/complete-profile'
    | '/auth/login'
    | '/auth/select-role'
    | '/semilleros/$idSemillero'
    | '/semilleros/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analitica'
    | '/compatibilidad'
    | '/postulaciones'
    | '/auth/complete-profile'
    | '/auth/login'
    | '/auth/select-role'
    | '/semilleros/$idSemillero'
    | '/semilleros'
  id:
    | '__root__'
    | '/'
    | '/analitica'
    | '/compatibilidad'
    | '/postulaciones'
    | '/auth/complete-profile'
    | '/auth/login'
    | '/auth/select-role'
    | '/semilleros/$idSemillero'
    | '/semilleros/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnaliticaRoute: typeof AnaliticaRoute
  CompatibilidadRoute: typeof CompatibilidadRoute
  PostulacionesRoute: typeof PostulacionesRoute
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSelectRoleRoute: typeof AuthSelectRoleRoute
  SemillerosIdSemilleroRoute: typeof SemillerosIdSemilleroRoute
  SemillerosIndexRoute: typeof SemillerosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analitica': {
      id: '/analitica'
      path: '/analitica'
      fullPath: '/analitica'
      preLoaderRoute: typeof AnaliticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compatibilidad': {
      id: '/compatibilidad'
      path: '/compatibilidad'
      fullPath: '/compatibilidad'
      preLoaderRoute: typeof CompatibilidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postulaciones': {
      id: '/postulaciones'
      path: '/postulaciones'
      fullPath: '/postulaciones'
      preLoaderRoute: typeof PostulacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete-profile': {
      id: '/auth/complete-profile'
      path: '/auth/complete-profile'
      fullPath: '/auth/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/select-role': {
      id: '/auth/select-role'
      path: '/auth/select-role'
      fullPath: '/auth/select-role'
      preLoaderRoute: typeof AuthSelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semilleros/': {
      id: '/semilleros/'
      path: '/semilleros'
      fullPath: '/semilleros/'
      preLoaderRoute: typeof SemillerosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semilleros/$idSemillero': {
      id: '/semilleros/$idSemillero'
      path: '/semilleros/$idSemillero'
      fullPath: '/semilleros/$idSemillero'
      preLoaderRoute: typeof SemillerosIdSemilleroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnaliticaRoute: AnaliticaRoute,
  CompatibilidadRoute: CompatibilidadRoute,
  PostulacionesRoute: PostulacionesRoute,
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSelectRoleRoute: AuthSelectRoleRoute,
  SemillerosIdSemilleroRoute: SemillerosIdSemilleroRoute,
  SemillerosIndexRoute: SemillerosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
