spring.application.name=agora-backend
# Credenciales de Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# URL de tu frontend
app.frontend.url=http://localhost:3000

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000