spring.application.name=agora-backend
spring.config.import=optional:file:.env
# Credenciales de Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# URL frontend
app.frontend.url=http://localhost:3000

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Configuración de Base de Datos (Supabase / PostgreSQL)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# para que Spring Boot no intente sobreescribirlas.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true